app:
  port: 3000
  env: development
  sessionSecret: mySuperSecret
  mongoUri: 'mongodb://localhost:27017/oldphonedeals?replicaSet=rs0'
  defaultPassword: "SecurePass1!"
  jwtSecret: LouisTheMagnificentSecretKey

admin:
  username: admin
  password: admin123

email:
  user: "louisliu330@gmail.com"
  pass: "ingwieqsnbnlismk"  